mutation mergeCarts(
  $savedCart: String
  $currentCart: String
  $strategy: String
) {
  orderForm: mergeCarts(
    savedCart: $savedCart
    currentCart: $currentCart
    strategy: $strategy
  )
}
