mutation mergeCarts(
  $savedCart: String!
  $currentCart: String!
  $strategy: Strategy
  $userId: String!
) {
  newOrderForm: mergeCarts(
    savedCart: $savedCart
    currentCart: $currentCart
    strategy: $strategy
    userId: $userId
  )
}
