mutation replaceCart(
  $savedCart: String!
  $currentCart: String!
  $strategy: Strategy!
) {
  newOrderForm: replaceCart(
    savedCart: $savedCart
    currentCart: $currentCart
    strategy: $strategy
  )
}
