mutation replaceCart(
  $savedCart: String!
  $currentCart: String!
  $hasToCombine: Boolean
) {
  newOrderForm: replaceCart(
    savedCart: $savedCart
    currentCart: $currentCart
    hasToCombine: $hasToCombine
  )
}
