mutation saveCurrentCart($userId: String!, $userType: String, $salesChannel: String!, $orderFormId: String) {
  saveCurrentCart(userId: $userId, userType: $userType, salesChannel: $salesChannel orderFormId: $orderFormId)
}
